CREATE TABLE [Soporte].[Customer180427] (
    [IdCustomer]                   INT             IDENTITY (1, 1) NOT NULL,
    [IdAgentCreatedBy]             INT             NOT NULL,
    [IdCustomerIdentificationType] INT             NULL,
    [IdGenericStatus]              INT             NOT NULL,
    [Name]                         NVARCHAR (MAX)  NOT NULL,
    [FirstLastName]                NVARCHAR (MAX)  NOT NULL,
    [SecondLastName]               NVARCHAR (MAX)  NOT NULL,
    [Address]                      NVARCHAR (MAX)  NOT NULL,
    [City]                         NVARCHAR (MAX)  NOT NULL,
    [State]                        NVARCHAR (MAX)  NOT NULL,
    [Country]                      NVARCHAR (MAX)  NOT NULL,
    [Zipcode]                      NVARCHAR (MAX)  NOT NULL,
    [PhoneNumber]                  NVARCHAR (MAX)  NULL,
    [CelullarNumber]               NVARCHAR (MAX)  NULL,
    [SSNumber]                     NVARCHAR (MAX)  NULL,
    [BornDate]                     DATETIME        NULL,
    [Occupation]                   NVARCHAR (MAX)  NULL,
    [IdentificationNumber]         NVARCHAR (MAX)  NULL,
    [PhysicalIdCopy]               INT             NULL,
    [DateOfLastChange]             DATETIME        NOT NULL,
    [EnterByIdUser]                INT             NOT NULL,
    [ExpirationIdentification]     DATETIME        NULL,
    [IdCarrier]                    INT             NULL,
    [IdentificationIdCountry]      INT             NULL,
    [IdentificationIdState]        INT             NULL,
    [SentAverage]                  DECIMAL (18, 2) NOT NULL,
    [FullName]                     NVARCHAR (120)  NULL,
    [IdCountryOfBirth]             INT             NULL,
    [ReceiveSms]                   BIT             NOT NULL,
    [CreationDate]                 DATETIME        NULL,
    [OccupationDetail]             NVARCHAR (MAX)  NULL,
    [idElasticCustomer]            VARCHAR (MAX)   NULL
);

