CREATE TABLE [dbo].[AgentMirror] (
    [Id]                                 INT            IDENTITY (1, 1) NOT NULL,
    [IdAgent]                            INT            NOT NULL,
    [IdAgentCommunication]               INT            NOT NULL,
    [IdAgentType]                        INT            NOT NULL,
    [IdUserSeller]                       INT            NOT NULL,
    [IdUserOpeningSalesRep]              INT            NULL,
    [IdAgentStatus]                      INT            NOT NULL,
    [IdAgentPaymentSchema]               INT            NOT NULL,
    [IdAgentReceiptType]                 INT            NULL,
    [IdAgentBankDeposit]                 INT            NULL,
    [AgentName]                          NVARCHAR (MAX) NOT NULL,
    [AgentCode]                          NVARCHAR (MAX) NOT NULL,
    [AgentAddress]                       NVARCHAR (MAX) NOT NULL,
    [AgentCity]                          NVARCHAR (MAX) NOT NULL,
    [AgentState]                         NVARCHAR (MAX) NOT NULL,
    [AgentZipcode]                       NVARCHAR (MAX) NOT NULL,
    [AgentPhone]                         NVARCHAR (MAX) NOT NULL,
    [AgentFax]                           NVARCHAR (MAX) NOT NULL,
    [AgentEmail]                         NVARCHAR (MAX) NOT NULL,
    [AgentContact]                       NVARCHAR (MAX) NOT NULL,
    [AgentTimeInBusiness]                NVARCHAR (MAX) NOT NULL,
    [AgentBusinessType]                  NVARCHAR (MAX) NOT NULL,
    [GuarantorName]                      NVARCHAR (MAX) NULL,
    [GuarantorLastName]                  NVARCHAR (MAX) NULL,
    [GuarantorSecondLastName]            NVARCHAR (MAX) NULL,
    [GuarantorAddress]                   NVARCHAR (MAX) NULL,
    [GuarantorCity]                      NVARCHAR (MAX) NULL,
    [GuarantorState]                     NVARCHAR (MAX) NULL,
    [GuarantorZipcode]                   NVARCHAR (MAX) NULL,
    [GuarantorPhone]                     NVARCHAR (MAX) NULL,
    [GuarantorCel]                       NVARCHAR (MAX) NULL,
    [GuarantorEmail]                     NVARCHAR (MAX) NULL,
    [GuarantorSSN]                       NVARCHAR (MAX) NULL,
    [GuarantorIdType]                    NVARCHAR (MAX) NULL,
    [GuarantorIdNumber]                  NVARCHAR (MAX) NULL,
    [GuarantorIdExpirationDate]          DATE           NULL,
    [GuarantorBornDate]                  DATE           NULL,
    [TaxID]                              NVARCHAR (MAX) NOT NULL,
    [CreditAmount]                       MONEY          NOT NULL,
    [AmountRequiredToAskId]              MONEY          NOT NULL,
    [CreationDate]                       DATETIME       NOT NULL,
    [OpenDate]                           DATETIME       NOT NULL,
    [Notes]                              NVARCHAR (MAX) NOT NULL,
    [CloseDate]                          DATETIME       NOT NULL,
    [BusinessPermissionNumber]           NVARCHAR (MAX) NULL,
    [BusinessPermissionExpiration]       DATE           NULL,
    [DoneOnSundayPayOn]                  INT            NOT NULL,
    [DoneOnMondayPayOn]                  INT            NOT NULL,
    [DoneOnTuesdayPayOn]                 INT            NOT NULL,
    [DoneOnWednesdayPayOn]               INT            NOT NULL,
    [DoneOnThursdayPayOn]                INT            NOT NULL,
    [DoneOnFridayPayOn]                  INT            NOT NULL,
    [DoneOnSaturdayPayOn]                INT            NOT NULL,
    [DateOfLastChange]                   DATETIME       NOT NULL,
    [EnterByIdUser]                      INT            NOT NULL,
    [SwitchCommission]                   BIT            NOT NULL,
    [SwitchExrate]                       BIT            NOT NULL,
    [CommissionTop]                      MONEY          NOT NULL,
    [CommissionBottom]                   MONEY          NOT NULL,
    [ExrateTop]                          MONEY          NOT NULL,
    [ExrateBottom]                       MONEY          NOT NULL,
    [ACHWellsFargo]                      BIT            NULL,
    [ShowAgentProfitWhenSendingTransfer] BIT            NOT NULL,
    [GuarantorBornCountry]               NVARCHAR (MAX) NULL,
    [ExcludeReportSignatureHold]         BIT            NOT NULL,
    [ExcludeReportExRates]               BIT            NOT NULL,
    [InsertDate]                         DATETIME       NOT NULL,
    [Action]                             VARCHAR (10)   NOT NULL,
    [IdAgentClass]                       INT            DEFAULT ((2)) NOT NULL,
    [IdOwner]                            INT            DEFAULT ((1)) NULL,
    [IdAgentCollectType]                 INT            DEFAULT ((4)) NOT NULL,
    [AccountNumber]                      NVARCHAR (MAX) NULL,
    [RoutingNumber]                      NVARCHAR (MAX) NULL,
    [RetainMoneyCommission]              BIT            DEFAULT ((0)) NOT NULL,
    [ShowLogo]                           BIT            NULL,
    [CancelReturnCommission]             BIT            NULL,
    [DoingBusinessAs]                    NVARCHAR (MAX) NULL,
    [IdAgentCommissionPay]               INT            NULL,
    [SubAccount]                         NVARCHAR (MAX) NULL,
    [AccountNumberCommission]            NVARCHAR (MAX) NULL,
    [RoutingNumberCommission]            NVARCHAR (MAX) NULL,
    [UsePin]                             BIT            DEFAULT ((0)) NOT NULL,
    [UsePayNow]                          BIT            DEFAULT ((0)) NOT NULL,
    [IdCounty]                           INT            NULL,
    [IdCountyGuarantor]                  INT            NULL,
    [SuspendedDatePendingFile]           DATETIME       NULL,
    [BlockPhoneTransactions]             BIT            NULL,
    [MoneyAlertInvitation]               BIT            DEFAULT ((0)) NOT NULL,
    [IdTimeZone]                         INT            NULL,
    [NeedsWFSubaccount]                  BIT            DEFAULT ((0)) NOT NULL,
    [NeedsWFSubaccountDate]              DATETIME       DEFAULT ('19000101') NOT NULL,
    [NeedsWFSubaccountIduser]            INT            DEFAULT ((0)) NOT NULL,
    [RequestWFSubaccount]                BIT            DEFAULT ((0)) NOT NULL,
    [RequestWFSubaccountDate]            DATETIME       DEFAULT ('19000101') NOT NULL,
    [RequestWFSubaccountIdUser]          INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AgentMirror] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_AgentMirror_IdAgent]
    ON [dbo].[AgentMirror]([IdAgent] ASC, [InsertDate] ASC)
    INCLUDE([Id], [IdAgentStatus], [IdAgentPaymentSchema], [RetainMoneyCommission], [IdAgentCommissionPay]);

