CREATE TABLE [dbo].[AgentAppW9Information] (
    [IdAgentAppW9Information]      INT            IDENTITY (1, 1) NOT NULL,
    [IdAgentApplication]           INT            NOT NULL,
    [Name]                         NVARCHAR (MAX) NOT NULL,
    [LastName]                     NVARCHAR (MAX) NOT NULL,
    [SecondLastName]               NVARCHAR (MAX) NULL,
    [BusinessName]                 NVARCHAR (MAX) NOT NULL,
    [Addreess]                     NVARCHAR (MAX) NOT NULL,
    [Ssn]                          NVARCHAR (MAX) NULL,
    [City]                         NVARCHAR (MAX) NULL,
    [State]                        NVARCHAR (MAX) NULL,
    [ZipCode]                      NVARCHAR (MAX) NULL,
    [ExemptPayee]                  BIT            NULL,
    [RequesterName]                NVARCHAR (MAX) NULL,
    [RequesterLastName]            NVARCHAR (MAX) NULL,
    [RequesterSecondLastName]      NVARCHAR (MAX) NULL,
    [RequesterAddress]             NVARCHAR (MAX) NULL,
    [TypeIndividual]               BIT            NULL,
    [TypeCorporation]              BIT            NULL,
    [TypeParthership]              BIT            NULL,
    [TypeLimitedLiability]         BIT            NULL,
    [TypeLimitedLiabilityType]     NVARCHAR (MAX) NULL,
    [Other]                        BIT            NULL,
    [OtherDescription]             NVARCHAR (MAX) NULL,
    [EnterByIdUser]                INT            NOT NULL,
    [DateOfLastChange]             DATETIME       NOT NULL,
    [EmployerIdentificationNumber] NVARCHAR (MAX) NULL,
    [ListAccountNumbers]           NVARCHAR (MAX) NULL,
    [CorporationCategory]          NVARCHAR (5)   NULL,
    [TypeTrust]                    BIT            DEFAULT ((0)) NULL,
    [ExemptPayeeCode]              NVARCHAR (10)  NULL,
    [ExemptReportingCode]          NVARCHAR (10)  NULL,
    CONSTRAINT [PK_AgentAppW9Information] PRIMARY KEY CLUSTERED ([IdAgentAppW9Information] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AgentW9Information_Application] FOREIGN KEY ([IdAgentApplication]) REFERENCES [dbo].[AgentApplications] ([IdAgentApplication]),
    CONSTRAINT [FK_AgentW9Information_Users] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser])
);

