CREATE TABLE [dbo].[Agent] (
    [IdAgent]                            INT            IDENTITY (1, 1) NOT NULL,
    [IdAgentCommunication]               INT            NOT NULL,
    [IdAgentType]                        INT            NOT NULL,
    [IdUserSeller]                       INT            NOT NULL,
    [IdUserOpeningSalesRep]              INT            NULL,
    [IdAgentStatus]                      INT            NOT NULL,
    [IdAgentPaymentSchema]               INT            NOT NULL,
    [IdAgentReceiptType]                 INT            NULL,
    [IdAgentBankDeposit]                 INT            NULL,
    [AgentName]                          NVARCHAR (MAX) NOT NULL,
    [AgentCode]                          NVARCHAR (MAX) NOT NULL,
    [AgentAddress]                       NVARCHAR (MAX) NOT NULL,
    [AgentCity]                          NVARCHAR (MAX) NOT NULL,
    [AgentState]                         VARCHAR (5)    NULL,
    [AgentZipcode]                       NVARCHAR (MAX) NOT NULL,
    [AgentPhone]                         NVARCHAR (MAX) NOT NULL,
    [AgentFax]                           NVARCHAR (MAX) NOT NULL,
    [AgentEmail]                         NVARCHAR (MAX) NOT NULL,
    [AgentContact]                       NVARCHAR (MAX) NOT NULL,
    [AgentTimeInBusiness]                NVARCHAR (MAX) NOT NULL,
    [AgentBusinessType]                  NVARCHAR (MAX) NOT NULL,
    [GuarantorName]                      NVARCHAR (MAX) NULL,
    [GuarantorLastName]                  NVARCHAR (MAX) NULL,
    [GuarantorSecondLastName]            NVARCHAR (MAX) NULL,
    [GuarantorAddress]                   NVARCHAR (MAX) NULL,
    [GuarantorCity]                      NVARCHAR (MAX) NULL,
    [GuarantorState]                     NVARCHAR (MAX) NULL,
    [GuarantorZipcode]                   NVARCHAR (MAX) NULL,
    [GuarantorPhone]                     NVARCHAR (MAX) NULL,
    [GuarantorCel]                       NVARCHAR (MAX) NULL,
    [GuarantorEmail]                     NVARCHAR (MAX) NULL,
    [GuarantorSSN]                       NVARCHAR (MAX) NULL,
    [GuarantorIdType]                    NVARCHAR (MAX) NULL,
    [GuarantorIdNumber]                  NVARCHAR (MAX) NULL,
    [GuarantorIdExpirationDate]          DATE           NULL,
    [GuarantorBornDate]                  DATE           NULL,
    [TaxID]                              NVARCHAR (MAX) NOT NULL,
    [CreditAmount]                       MONEY          NOT NULL,
    [AmountRequiredToAskId]              MONEY          NOT NULL,
    [CreationDate]                       DATETIME       NOT NULL,
    [OpenDate]                           DATETIME       NOT NULL,
    [Notes]                              NVARCHAR (MAX) NOT NULL,
    [CloseDate]                          DATETIME       NOT NULL,
    [BusinessPermissionNumber]           NVARCHAR (MAX) NULL,
    [BusinessPermissionExpiration]       DATE           NULL,
    [DoneOnSundayPayOn]                  INT            NOT NULL,
    [DoneOnMondayPayOn]                  INT            NOT NULL,
    [DoneOnTuesdayPayOn]                 INT            NOT NULL,
    [DoneOnWednesdayPayOn]               INT            NOT NULL,
    [DoneOnThursdayPayOn]                INT            NOT NULL,
    [DoneOnFridayPayOn]                  INT            NOT NULL,
    [DoneOnSaturdayPayOn]                INT            NOT NULL,
    [DateOfLastChange]                   DATETIME       NOT NULL,
    [EnterByIdUser]                      INT            NOT NULL,
    [SwitchCommission]                   BIT            NOT NULL,
    [SwitchExrate]                       BIT            NOT NULL,
    [CommissionTop]                      MONEY          NOT NULL,
    [CommissionBottom]                   MONEY          NOT NULL,
    [ExrateTop]                          MONEY          NOT NULL,
    [ExrateBottom]                       MONEY          NOT NULL,
    [ACHWellsFargo]                      BIT            DEFAULT ((0)) NULL,
    [ShowAgentProfitWhenSendingTransfer] BIT            NOT NULL,
    [GuarantorBornCountry]               NVARCHAR (MAX) NULL,
    [ExcludeReportSignatureHold]         BIT            NOT NULL,
    [ExcludeReportExRates]               BIT            NOT NULL,
    [ShowLogo]                           BIT            CONSTRAINT [DF_Agent_ShowLogo] DEFAULT ((0)) NULL,
    [CancelReturnCommission]             BIT            CONSTRAINT [DF__Agent__CancelRet__697C9932] DEFAULT ((1)) NOT NULL,
    [IdAgentClass]                       INT            DEFAULT ((2)) NOT NULL,
    [IdOwner]                            INT            DEFAULT ((1)) NULL,
    [IdAgentCollectType]                 INT            DEFAULT ((4)) NOT NULL,
    [AccountNumber]                      NVARCHAR (MAX) NULL,
    [RoutingNumber]                      NVARCHAR (MAX) NULL,
    [RetainMoneyCommission]              BIT            DEFAULT ((0)) NOT NULL,
    [DoingBusinessAs]                    NVARCHAR (MAX) NULL,
    [IdAgentCommissionPay]               INT            NULL,
    [SubAccount]                         NVARCHAR (MAX) NULL,
    [AccountNumberCommission]            NVARCHAR (MAX) NULL,
    [RoutingNumberCommission]            NVARCHAR (MAX) NULL,
    [UsePin]                             BIT            DEFAULT ((0)) NOT NULL,
    [UsePayNow]                          BIT            DEFAULT ((0)) NOT NULL,
    [IdCounty]                           INT            NULL,
    [IdCountyGuarantor]                  INT            NULL,
    [SuspendedDatePendingFile]           DATETIME       NULL,
    [BlockPhoneTransactions]             BIT            NULL,
    [MoneyAlertInvitation]               BIT            DEFAULT ((0)) NOT NULL,
    [CheckEditMicr]                      BIT            CONSTRAINT [df_ConstraintMicr] DEFAULT ((0)) NOT NULL,
    [NoteCreditAmountChange]             VARCHAR (MAX)  NULL,
    [IdTimeZone]                         INT            NULL,
    [OfacBusinessChecked]                BIT            NULL,
    [OfacGuarantorChecked]               BIT            NULL,
    [OfacOwnerChecked]                   BIT            NULL,
    [NeedsWFSubaccount]                  BIT            DEFAULT ((0)) NOT NULL,
    [NeedsWFSubaccountDate]              DATETIME       DEFAULT ('19000101') NOT NULL,
    [NeedsWFSubaccountIduser]            INT            DEFAULT ((0)) NOT NULL,
    [RequestWFSubaccount]                BIT            DEFAULT ((0)) NOT NULL,
    [RequestWFSubaccountDate]            DATETIME       DEFAULT ('19000101') NOT NULL,
    [RequestWFSubaccountIdUser]          INT            DEFAULT ((0)) NOT NULL,
    [IdAgentsReportWellsFargo]           INT            DEFAULT ((0)) NOT NULL,
    [StateCode]                          VARCHAR (MAX)  NULL,
    [IdLogAccVerif]                      INT            NULL,
    [IdAgentGroup]                       INT            NULL,
    [IsSwitchSpecExRateGroup]            BIT            DEFAULT ((0)) NOT NULL,
    [ExpirationDateExRateGroup]          DATETIME       NULL,
    [ApplyKYCRules]                      BIT            NULL,
    [IdAgentEntityType]                  INT            NULL,
    [IdAgentTaxIdType]                   INT            NULL,
    [AgentBusinessEmail]                 VARCHAR (100)  NULL,
    [AgentBusinessWebsite]               VARCHAR (150)  NULL,
    [AgentFinCENReg]                     BIT            DEFAULT ((0)) NULL,
    [AgentFinCENRegExpiration]           DATE           NULL,
    [AgentCheckCasher]                   BIT            DEFAULT ((0)) NULL,
    [AgentCheckLicense]                  BIT            DEFAULT ((0)) NULL,
    [AgentCheckLicenseNumber]            VARCHAR (50)   NULL,
    [MailCheckTo]                        VARCHAR (20)   NULL,
    [ComplianceOfficerDateOfBirth]       DATE           NULL,
    [ComplianceOfficerPlaceOfBirth]      VARCHAR (250)  NULL,
    [ComplianceOfficerName]              VARCHAR (200)  NULL,
    [IdAgentBusinessType]                INT            NULL,
    [IdTaxIDType]                        INT            NULL,
    [OfacComplianceOfficerChecked]       BIT            NULL,
    CONSTRAINT [PK_Agent] PRIMARY KEY CLUSTERED ([IdAgent] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Agent_AgentBankDeposit] FOREIGN KEY ([IdAgentBankDeposit]) REFERENCES [dbo].[AgentBankDeposit] ([IdAgentBankDeposit]),
    CONSTRAINT [FK_Agent_AgentBusinessType] FOREIGN KEY ([IdAgentBusinessType]) REFERENCES [dbo].[AgentBusinessTypes] ([IdAgentBusinessType]),
    CONSTRAINT [FK_Agent_AgentClass] FOREIGN KEY ([IdAgentClass]) REFERENCES [dbo].[AgentClass] ([IdAgentClass]),
    CONSTRAINT [FK_Agent_AgentCollectType] FOREIGN KEY ([IdAgentCollectType]) REFERENCES [dbo].[AgentCollectType] ([IdAgentCollectType]),
    CONSTRAINT [FK_Agent_AgentCommunication] FOREIGN KEY ([IdAgentCommunication]) REFERENCES [dbo].[AgentCommunication] ([IdAgentCommunication]),
    CONSTRAINT [FK_Agent_AgentGroup] FOREIGN KEY ([IdAgentGroup]) REFERENCES [dbo].[AgentGroup] ([IdAgentGroup]),
    CONSTRAINT [FK_Agent_AgentPaymentSchema] FOREIGN KEY ([IdAgentPaymentSchema]) REFERENCES [dbo].[AgentPaymentSchema] ([IdAgentPaymentSchema]),
    CONSTRAINT [FK_Agent_AgentReceiptType] FOREIGN KEY ([IdAgentReceiptType]) REFERENCES [dbo].[AgentReceiptType] ([IdAgentReceiptType]),
    CONSTRAINT [FK_Agent_AgentStatus] FOREIGN KEY ([IdAgentStatus]) REFERENCES [dbo].[AgentStatus] ([IdAgentStatus]),
    CONSTRAINT [FK_Agent_AgentType] FOREIGN KEY ([IdAgentType]) REFERENCES [dbo].[AgentType] ([IdAgentType]),
    CONSTRAINT [FK_Agent_IdAgentCommissionPay] FOREIGN KEY ([IdAgentCommissionPay]) REFERENCES [dbo].[AgentCommissionPay] ([IdAgentCommissionPay]),
    CONSTRAINT [FK_Agent_Owner] FOREIGN KEY ([IdOwner]) REFERENCES [dbo].[Owner] ([IdOwner]),
    CONSTRAINT [FK_Agent_TaxIDType] FOREIGN KEY ([IdTaxIDType]) REFERENCES [Corp].[TaxIDType] ([IdTaxIDType]),
    CONSTRAINT [FK_Agent_Users] FOREIGN KEY ([IdUserSeller]) REFERENCES [dbo].[Users] ([IdUser]),
    CONSTRAINT [FK_Agent_Users1] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser]),
    CONSTRAINT [FK_Agent_Users2] FOREIGN KEY ([IdUserOpeningSalesRep]) REFERENCES [dbo].[Users] ([IdUser]),
    CONSTRAINT [FK_Agent_Users3] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser])
);


GO
CREATE NONCLUSTERED INDEX [IX_Agent_IdAgentStatus]
    ON [dbo].[Agent]([IdAgentStatus] ASC)
    INCLUDE([IdAgent], [AgentCode], [IdAgentPaymentSchema], [IdAgentCommissionPay], [IdAgentCommunication], [IdOwner]);


GO
CREATE NONCLUSTERED INDEX [IX_Agent_IdOwner]
    ON [dbo].[Agent]([IdOwner] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Agent_ShowLogo]
    ON [dbo].[Agent]([ShowLogo] ASC)
    INCLUDE([IdAgent]);


GO
CREATE NONCLUSTERED INDEX [IX_Agent_IdAgentClass]
    ON [dbo].[Agent]([IdAgentClass] ASC)
    INCLUDE([IdAgent], [IdUserSeller], [IdAgentStatus], [AgentState]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Monto requerido para pedir ID', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Agent', @level2type = N'COLUMN', @level2name = N'AmountRequiredToAskId';

