CREATE TABLE [dbo].[AgentApplication] (
    [IdAgentApplication]              INT            IDENTITY (1, 1) NOT NULL,
    [IdAgentApplicationCommunication] INT            NOT NULL,
    [IdUserSeller]                    INT            NOT NULL,
    [IdAgentApplicationStatus]        INT            NOT NULL,
    [IdAgentApplicationReceiptType]   INT            NOT NULL,
    [IdAgentApplicationBankDeposit]   INT            NULL,
    [IdAgentBusinessType]             INT            NOT NULL,
    [AgentName]                       NVARCHAR (MAX) NOT NULL,
    [AgentCode]                       NVARCHAR (MAX) NOT NULL,
    [AgentAddress]                    NVARCHAR (MAX) NOT NULL,
    [AgentCity]                       NVARCHAR (MAX) NOT NULL,
    [AgentState]                      NVARCHAR (MAX) NOT NULL,
    [AgentZipCode]                    NVARCHAR (MAX) NOT NULL,
    [AgentPhone]                      NVARCHAR (MAX) NOT NULL,
    [AgentFax]                        NVARCHAR (MAX) NOT NULL,
    [AgentContact]                    NVARCHAR (MAX) NOT NULL,
    [AgentTimeInBusiness]             DATETIME       NULL,
    [AgentActivity]                   NVARCHAR (MAX) NULL,
    [GuarantorName]                   NVARCHAR (MAX) NULL,
    [GuarantorLastName]               NVARCHAR (MAX) NULL,
    [GuarantorSecondLastName]         NVARCHAR (MAX) NULL,
    [GuarantorAddress]                NVARCHAR (MAX) NULL,
    [GuarantorCity]                   NVARCHAR (MAX) NULL,
    [GuarantorState]                  NVARCHAR (MAX) NULL,
    [GuarantorZipCode]                NVARCHAR (MAX) NULL,
    [GuarantorPhone]                  NVARCHAR (MAX) NULL,
    [GuarantorCel]                    NVARCHAR (MAX) NULL,
    [GuarantorEmail]                  NVARCHAR (MAX) NULL,
    [GuarantorSsn]                    NVARCHAR (MAX) NULL,
    [GuarantorIdType]                 INT            NULL,
    [GuarantorIdNumber]               NVARCHAR (MAX) NULL,
    [GuarantorIdExpirationDate]       DATE           NULL,
    [GuarantorBornDate]               DATE           NULL,
    [GuarantorCreditScore]            NVARCHAR (MAX) NULL,
    [GuarantorBornCountry]            NVARCHAR (MAX) NULL,
    [GuarantorTitle]                  NVARCHAR (MAX) NULL,
    [TaxId]                           NVARCHAR (MAX) NOT NULL,
    [Notes]                           NVARCHAR (MAX) NOT NULL,
    [BusinessPermissionNumber]        NVARCHAR (MAX) NOT NULL,
    [BusinessPermissionExpiration]    DATE           NOT NULL,
    [DoneOnSundayPayOn]               INT            NOT NULL,
    [DoneOnMondayPayOn]               INT            NOT NULL,
    [DoneOnTuesdayPayOn]              INT            NOT NULL,
    [DoneOnWednesdayPayOn]            INT            NOT NULL,
    [DoneOnThursdayPayOn]             INT            NOT NULL,
    [DoneOnFridayPayOn]               INT            NOT NULL,
    [DoneOnSaturdayPayOn]             INT            NOT NULL,
    [CommissionAgent]                 DECIMAL (5, 2) NOT NULL,
    [CommissionCorp]                  DECIMAL (5, 2) NOT NULL,
    [HasBillPayment]                  BIT            NOT NULL,
    [HasFlexStatus]                   BIT            NOT NULL,
    [DateOfLastChange]                DATETIME       NOT NULL,
    [EnterByIdUser]                   INT            NOT NULL,
    [HasAch]                          BIT            NOT NULL,
    [DateOfCreation]                  DATETIME       NOT NULL,
    [OfacOwnerChecked]                BIT            NULL,
    [OfacGuarantorChecked]            BIT            NULL,
    [OfacBusinessChecked]             BIT            NULL,
    [CommissionAgentOtherCountries]   DECIMAL (5, 2) NOT NULL,
    [CommissionCorpOtherCountries]    DECIMAL (5, 2) NOT NULL,
    [IdOwner]                         INT            NULL,
    [IdAgentClass]                    INT            NULL,
    [DoingBusinessAs]                 NVARCHAR (MAX) NULL,
    [IdAgentPaymentSchema]            INT            NOT NULL,
    [RetainMoneyCommission]           BIT            NOT NULL,
    [IdAgentCommissionPay]            INT            NULL,
    [AccountNumberCommission]         NVARCHAR (MAX) NULL,
    [RoutingNumberCommission]         NVARCHAR (MAX) NULL,
    [IdCounty]                        INT            NULL,
    [IdCountyGuarantor]               INT            NULL,
    [NeedsWFSubaccount]               BIT            NOT NULL,
    [RequestWFSubaccount]             BIT            NOT NULL,
    [NeedsWFSubaccountDate]           DATETIME       NOT NULL,
    [NeedsWFSubaccountIduser]         INT            NOT NULL,
    [RequestWFSubaccountDate]         DATETIME       NOT NULL,
    [RequestWFSubaccountIdUser]       INT            NOT NULL,
    [IdAgentsReportWellsFargo]        INT            NOT NULL,
    [IsVerifiedAddress]               BIT            NULL,
    [ComplianceOfficerTitle]          VARCHAR (200)  NULL,
    [ComplianceOfficerName]           VARCHAR (200)  NULL,
    [TypeTaxID]                       INT            NULL
);

