CREATE TABLE [dbo].[CellularPurchaseTransactions] (
    [Id]                            INT             IDENTITY (1, 1) NOT NULL,
    [IdAgent]                       INT             NOT NULL,
    [IdUser]                        INT             NOT NULL,
    [TransactionDate]               DATETIME        NOT NULL,
    [IdProduct]                     INT             NOT NULL,
    [Description]                   NVARCHAR (MAX)  NULL,
    [Price]                         DECIMAL (18, 2) NOT NULL,
    [FeeAmount]                     DECIMAL (18, 2) NOT NULL,
    [Fee]                           DECIMAL (18, 2) NOT NULL,
    [IsFeePercentage]               BIT             NOT NULL,
    [CorpCommission]                DECIMAL (18, 2) NOT NULL,
    [AgentCommission]               DECIMAL (18, 2) NOT NULL,
    [Status]                        INT             NOT NULL,
    [Request]                       NVARCHAR (MAX)  NULL,
    [Response]                      NVARCHAR (MAX)  NULL,
    [RequestSku]                    INT             NOT NULL,
    [RequestApiUserName]            NVARCHAR (MAX)  NULL,
    [RequestApiPassword]            NVARCHAR (MAX)  NULL,
    [RequestTerminalType]           INT             NOT NULL,
    [RequestTerminalId]             NVARCHAR (MAX)  NULL,
    [RequestclerkId]                NVARCHAR (MAX)  NULL,
    [RequestCustTransId]            NVARCHAR (MAX)  NULL,
    [Balance]                       DECIMAL (18, 2) NOT NULL,
    [ResponsepGsTransId]            NVARCHAR (MAX)  NULL,
    [ResponseTransDateTime]         DATETIME        NOT NULL,
    [ResponseCustTransId]           NVARCHAR (MAX)  NULL,
    [ResponseTerminalDateTime]      DATETIME        NOT NULL,
    [ResponseControlNumber]         NVARCHAR (MAX)  NULL,
    [ResponsePinNumber]             NVARCHAR (MAX)  NULL,
    [ResponseDnis]                  NVARCHAR (MAX)  NULL,
    [ResponseCustomerServiceNumber] NVARCHAR (MAX)  NULL,
    [ResponseMessage]               NVARCHAR (MAX)  NULL,
    [LastChange_LastUserChange]     NVARCHAR (MAX)  NULL,
    [LastChange_LastDateChange]     DATETIME        NOT NULL,
    [LastChange_LastIpChange]       NVARCHAR (MAX)  NULL,
    [LastChange_LastNoteChange]     NVARCHAR (MAX)  NULL,
    [CancelDate]                    DATETIME        NULL,
    [CancelUser]                    INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CellularPurchaseTransaction_SelectedProduct] FOREIGN KEY ([IdProduct]) REFERENCES [dbo].[CellularProducts] ([IdCellularProduct])
);

