CREATE TABLE [dbo].[CellularRtrPurchaseTransactions] (
    [Id]                        INT             IDENTITY (1, 1) NOT NULL,
    [IdAgent]                   INT             NOT NULL,
    [IdUser]                    INT             NOT NULL,
    [TransactionDate]           DATETIME        NOT NULL,
    [IdCellularRtrProduct]      INT             NOT NULL,
    [Description]               NVARCHAR (MAX)  NULL,
    [PhoneNumber]               NVARCHAR (MAX)  NULL,
    [Amount]                    DECIMAL (18, 2) NOT NULL,
    [FeeAmount]                 DECIMAL (18, 2) NOT NULL,
    [Fee]                       DECIMAL (18, 2) NOT NULL,
    [IsFeePercentage]           BIT             NOT NULL,
    [CorpCommission]            DECIMAL (18, 2) NOT NULL,
    [AgentCommission]           DECIMAL (18, 2) NOT NULL,
    [Status]                    INT             NOT NULL,
    [CustZipCode]               NVARCHAR (MAX)  NULL,
    [Request]                   NVARCHAR (MAX)  NULL,
    [Response]                  NVARCHAR (MAX)  NULL,
    [RequestSku]                INT             NOT NULL,
    [RequestApiUserName]        NVARCHAR (MAX)  NULL,
    [RequestApiPassword]        NVARCHAR (MAX)  NULL,
    [RequestTerminalType]       INT             NOT NULL,
    [RequestTerminalId]         NVARCHAR (MAX)  NULL,
    [RequestClerkId]            NVARCHAR (MAX)  NULL,
    [RequestCustTransId]        NVARCHAR (MAX)  NULL,
    [ResponsePgsTransId]        NVARCHAR (MAX)  NULL,
    [ResponseTransDateTime]     DATETIME        NOT NULL,
    [ResponseTerminalDateTime]  DATETIME        NOT NULL,
    [ResponseMessage]           NVARCHAR (MAX)  NULL,
    [ResponseCustomerReceipt]   NVARCHAR (MAX)  NULL,
    [ResponseStatus]            NVARCHAR (MAX)  NULL,
    [LastChange_LastUserChange] NVARCHAR (MAX)  NULL,
    [LastChange_LastDateChange] DATETIME        NOT NULL,
    [LastChange_LastIpChange]   NVARCHAR (MAX)  NULL,
    [LastChange_LastNoteChange] NVARCHAR (MAX)  NULL,
    [CancelDate]                DATETIME        NULL,
    [CancelUser]                INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CellularRtrPurchaseTransaction_SelectedCellularRtrProduct] FOREIGN KEY ([IdCellularRtrProduct]) REFERENCES [dbo].[CellularRtrProducts] ([IdCellularProduct])
);

