CREATE TABLE [dbo].[CustomerMirror] (
    [IdCustomerMirror]             INT             IDENTITY (1, 1) NOT NULL,
    [IdCustomer]                   INT             NULL,
    [IdAgentCreatedBy]             INT             NULL,
    [IdCustomerIdentificationType] INT             NULL,
    [IdGenericStatus]              INT             NULL,
    [Name]                         NVARCHAR (40)   NULL,
    [FirstLastName]                NVARCHAR (40)   NULL,
    [SecondLastName]               NVARCHAR (40)   NULL,
    [Address]                      NVARCHAR (MAX)  NULL,
    [City]                         NVARCHAR (MAX)  NULL,
    [State]                        NVARCHAR (MAX)  NULL,
    [Country]                      NVARCHAR (MAX)  NULL,
    [Zipcode]                      NVARCHAR (MAX)  NULL,
    [PhoneNumber]                  NVARCHAR (15)   NULL,
    [CelullarNumber]               NVARCHAR (15)   NULL,
    [SSNumber]                     NVARCHAR (MAX)  NULL,
    [BornDate]                     DATETIME        NULL,
    [Occupation]                   NVARCHAR (MAX)  NULL,
    [IdentificationNumber]         NVARCHAR (MAX)  NULL,
    [PhysicalIdCopy]               INT             NULL,
    [DateOfLastChange]             DATETIME        NULL,
    [EnterByIdUser]                INT             NULL,
    [ExpirationIdentification]     DATETIME        NULL,
    [IdCarrier]                    INT             NULL,
    [IdentificationIdCountry]      INT             NULL,
    [IdentificationIdState]        INT             NULL,
    [SentAverage]                  DECIMAL (18, 2) NULL,
    [FullName]                     NVARCHAR (120)  NULL,
    [ReceiveSms]                   BIT             DEFAULT ((0)) NOT NULL,
    [CreationDate]                 DATETIME        NULL,
    [OccupationDetail]             NVARCHAR (MAX)  DEFAULT (NULL) NULL,
    [IdOccupation]                 INT             NULL,
    [IdSubcategoryOccupation]      INT             NULL,
    [SubcategoryOccupationOther]   VARCHAR (50)    NULL,
    CONSTRAINT [PK_ICustomerMirror] PRIMARY KEY CLUSTERED ([IdCustomerMirror] ASC) WITH (FILLFACTOR = 90)
);

