CREATE TABLE [dbo].[Owner] (
    [IdOwner]           INT            IDENTITY (1, 1) NOT NULL,
    [Name]              NVARCHAR (MAX) NULL,
    [LastName]          NVARCHAR (MAX) NULL,
    [SecondLastName]    NVARCHAR (MAX) NULL,
    [Address]           NVARCHAR (MAX) NULL,
    [City]              NVARCHAR (MAX) NULL,
    [State]             NVARCHAR (MAX) NULL,
    [Zipcode]           NVARCHAR (MAX) NULL,
    [Phone]             NVARCHAR (MAX) NULL,
    [Cel]               NVARCHAR (MAX) NULL,
    [Email]             NVARCHAR (MAX) NULL,
    [SSN]               NVARCHAR (MAX) NULL,
    [IdType]            NVARCHAR (MAX) NULL,
    [IdNumber]          NVARCHAR (MAX) NULL,
    [IdExpirationDate]  DATE           NULL,
    [BornDate]          DATE           NULL,
    [BornCountry]       NVARCHAR (MAX) NULL,
    [CreationDate]      DATETIME       NULL,
    [DateofLastChange]  DATETIME       NULL,
    [EnterByIdUser]     INT            NULL,
    [IdStatus]          INT            NULL,
    [CreditScore]       NVARCHAR (MAX) NULL,
    [IdCounty]          INT            NULL,
    [IdStateEmission]   INT            NULL,
    [IdCountryEmission] INT            NULL,
    [TypeTaxId]         INT            DEFAULT (NULL) NULL,
    CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED ([IdOwner] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Owner_GenericStatus] FOREIGN KEY ([IdStatus]) REFERENCES [dbo].[GenericStatus] ([IdGenericStatus]),
    CONSTRAINT [FK_Owner_Users] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser])
);

