CREATE TABLE [dbo].[PagosInt] (
    [PAY_AGENT_CD]         NVARCHAR (255) NULL,
    [PAY_AGENT_SD]         NVARCHAR (255) NULL,
    [PAY_AGENT_BRANCH_SD]  NVARCHAR (255) NULL,
    [PAY_AGENT_REGION_SD]  NVARCHAR (255) NULL,
    [PAY_AGENT_BRANCH_DS]  NVARCHAR (255) NULL,
    [PAY_AGENT_ADDRESS]    NVARCHAR (255) NULL,
    [PAY_AGENT_CITY]       NVARCHAR (255) NULL,
    [PAY_AGENT_ZIPCODE]    FLOAT (53)     NULL,
    [PAY_AGENT_STATE_CD]   NVARCHAR (255) NULL,
    [PAY_AGENT_COUNTRY_CD] NVARCHAR (255) NULL,
    [PAY_AGENT_PHONE]      FLOAT (53)     NULL,
    [PAY_AGENT_SCHEDULE]   NVARCHAR (255) NULL,
    [PAY_AGENT_SCHEDULE1]  NVARCHAR (255) NULL
);

