CREATE TABLE [dbo].[ProfitData] (
    [IdProfitData]                          INT      IDENTITY (1, 1) NOT NULL,
    [IdAgent]                               INT      NULL,
    [IdCountryCurrency]                     INT      NULL,
    [IdCountry]                             INT      NULL,
    [NumTrans]                              INT      NULL,
    [NumCancel]                             INT      NULL,
    [NumRej]                                INT      NULL,
    [UnclaimedNumTrans]                     INT      NULL,
    [CogsTrans]                             MONEY    NULL,
    [CogsCancel]                            MONEY    NULL,
    [CogsRej]                               MONEY    NULL,
    [UnclaimedCOGS]                         MONEY    NULL,
    [AmountTrans]                           MONEY    NULL,
    [AmountCancel]                          MONEY    NULL,
    [AmountRej]                             MONEY    NULL,
    [UnclaimedAmount]                       MONEY    NULL,
    [FxResult]                              MONEY    NULL,
    [FxResultCancel]                        MONEY    NULL,
    [FxResultRej]                           MONEY    NULL,
    [AgentcommissionMonthly]                MONEY    NULL,
    [AgentcommissionMonthlyCancel]          MONEY    NULL,
    [AgentcommissionMonthlyRej]             MONEY    NULL,
    [AgentcommissionRetain]                 MONEY    NULL,
    [AgentcommissionRetainCancel]           MONEY    NULL,
    [AgentcommissionRetainRej]              MONEY    NULL,
    [AgentcommissionRetainCancelLikeReject] MONEY    NULL,
    [IncomeFeeCancelLikeReject]             MONEY    NULL,
    [IncomeFee]                             MONEY    NULL,
    [IncomeFeeCancel]                       MONEY    NULL,
    [IncomeFeeRej]                          MONEY    NULL,
    [FxFee]                                 MONEY    NULL,
    [FxFeeCancel]                           MONEY    NULL,
    [FxFeeRej]                              MONEY    NULL,
    [FxFeeM]                                MONEY    NULL,
    [FxFeeMCancel]                          MONEY    NULL,
    [FxFeeMRej]                             MONEY    NULL,
    [FxFeeR]                                MONEY    NULL,
    [FxFeeRCancel]                          MONEY    NULL,
    [FxFeeRRej]                             MONEY    NULL,
    [BankCommission]                        MONEY    NULL,
    [BankCommissionCancel]                  MONEY    NULL,
    [BankCommissionRej]                     MONEY    NULL,
    [PayerCommission]                       MONEY    NULL,
    [PayerCommissionCancel]                 MONEY    NULL,
    [PayerCommissionRej]                    MONEY    NULL,
    [DateOfProfitData]                      DATETIME NULL,
    CONSTRAINT [PK_ProfitData] PRIMARY KEY CLUSTERED ([IdProfitData] ASC) WITH (FILLFACTOR = 90)
);

