CREATE TABLE [dbo].[SoftgateBillPaymentTransactions] (
    [IdBillPayment]           INT             NOT NULL,
    [Description]             NVARCHAR (MAX)  NULL,
    [BillerGroupId]           INT             NOT NULL,
    [BillerPaymentProviderId] INT             NOT NULL,
    [DuplicateEntryFlag]      BIT             NOT NULL,
    [VendorAccountLengthMin]  INT             NOT NULL,
    [VendorAccountLengthMax]  INT             NOT NULL,
    [VendorTranAmtMin]        DECIMAL (18, 2) NOT NULL,
    [VendorTranAmtMax]        DECIMAL (18, 2) NOT NULL,
    [CustomerNameRequired]    BIT             NOT NULL,
    [SenderNameRequired]      BIT             NOT NULL,
    [SenderRequiredAmountMin] DECIMAL (18, 2) NOT NULL,
    [PostingTimeMessage]      NVARCHAR (MAX)  NULL,
    [PresentmentFlag]         BIT             NOT NULL,
    [AcctNumOptional]         BIT             NOT NULL,
    [AltLookupLabel]          NVARCHAR (MAX)  NULL,
    [AltLookupVisibleLen]     INT             NOT NULL,
    [AltLookupMaxLen]         INT             NOT NULL,
    [AddInfoLabel1]           NVARCHAR (MAX)  NULL,
    [AddInfoReqFlag1]         BIT             NOT NULL,
    [AddInfoValType1]         NVARCHAR (MAX)  NULL,
    [AddInfoVisibleLen1]      INT             NOT NULL,
    [AddInfoMaxLen1]          INT             NOT NULL,
    [AddInfoLabel2]           NVARCHAR (MAX)  NULL,
    [AddInfoReqFlag2]         BIT             NOT NULL,
    [AddInfoValType2]         NVARCHAR (MAX)  NULL,
    [AddInfoVisibleLen2]      INT             NOT NULL,
    [AddInfoMaxLen2]          INT             NOT NULL,
    [MaskAccountOnReceipt]    BIT             NOT NULL,
    [MandatoryFee]            BIT             NOT NULL,
    [MandatoryFeeAmount]      MONEY           NOT NULL,
    PRIMARY KEY CLUSTERED ([IdBillPayment] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [BillPaymentSoftgate_TypeConstraint_From_BillPayment_To_SoftgateBillPaymentTransactions] FOREIGN KEY ([IdBillPayment]) REFERENCES [dbo].[BillPaymentTransactions] ([IdBillPayment])
);

