CREATE TABLE [dbo].[TransferClosedOnWhoseBehalf] (
    [IdTransferClosedOnWhoseBehalf] INT            NOT NULL,
    [IdAgentCreatedBy]              INT            NOT NULL,
    [IdGenericStatus]               INT            NOT NULL,
    [Name]                          NVARCHAR (MAX) NOT NULL,
    [FirstLastName]                 NVARCHAR (MAX) NOT NULL,
    [SecondLastName]                NVARCHAR (MAX) NOT NULL,
    [Address]                       NVARCHAR (MAX) NOT NULL,
    [City]                          NVARCHAR (MAX) NOT NULL,
    [State]                         NVARCHAR (MAX) NOT NULL,
    [Country]                       NVARCHAR (MAX) NOT NULL,
    [Zipcode]                       NVARCHAR (MAX) NOT NULL,
    [PhoneNumber]                   NVARCHAR (MAX) NOT NULL,
    [CelullarNumber]                NVARCHAR (MAX) NOT NULL,
    [SSNumber]                      NVARCHAR (MAX) NOT NULL,
    [BornDate]                      DATETIME       NULL,
    [Occupation]                    NVARCHAR (MAX) NOT NULL,
    [IdentificationNumber]          NVARCHAR (MAX) NOT NULL,
    [PhysicalIdCopy]                INT            NOT NULL,
    [IdCustomerIdentificationType]  INT            NULL,
    [ExpirationIdentification]      DATETIME       NULL,
    [Purpose]                       NVARCHAR (200) NOT NULL,
    [Relationship]                  NVARCHAR (200) NOT NULL,
    [MoneySource]                   NVARCHAR (200) NOT NULL,
    [DateOfLastChange]              DATETIME       NOT NULL,
    [EnterByIdUser]                 INT            NOT NULL,
    CONSTRAINT [PK_TransferClosedOnWhosBehalf] PRIMARY KEY CLUSTERED ([IdTransferClosedOnWhoseBehalf] ASC) WITH (FILLFACTOR = 90)
);

