CREATE TABLE [dbo].[WellsFargoReportDetailExcel] (
    [idWellsFargoReportDetailExcel] INT           IDENTITY (1, 1) NOT NULL,
    [IdAgentsReportWellsFargo]      INT           NULL,
    [Master_Account]                VARCHAR (MAX) NULL,
    [Master_Account_Name]           VARCHAR (MAX) NULL,
    [Master_Account_TIN]            VARCHAR (MAX) NULL,
    [Agent_Code]                    VARCHAR (MAX) NULL,
    [Agent_Address]                 VARCHAR (MAX) NULL,
    [City]                          VARCHAR (MAX) NULL,
    [Agents_Main_Revenue_Source]    VARCHAR (MAX) NULL,
    [Agent_Owner_1]                 VARCHAR (MAX) NULL,
    [Owner_1_First_Name]            VARCHAR (MAX) NULL,
    [Owner_1_Last_Name]             VARCHAR (MAX) NULL,
    [Owner_1_SSNTIN]                VARCHAR (MAX) NULL,
    [Owner_1_Street_Address]        VARCHAR (MAX) NULL,
    [Owner_1_City]                  VARCHAR (MAX) NULL,
    [Owner_1_State]                 VARCHAR (MAX) NULL,
    [Owner_1_Zip_Code]              VARCHAR (MAX) NULL,
    [Owner_1_Country]               VARCHAR (MAX) NULL,
    [Owner_1_Date_of_Birth]         VARCHAR (MAX) NULL,
    [Agent_Contact_Number]          VARCHAR (MAX) NULL,
    [State]                         VARCHAR (MAX) NULL,
    [ZIP_Code]                      VARCHAR (MAX) NULL,
    [Country]                       VARCHAR (MAX) NULL,
    [Agent_Entity_Type]             VARCHAR (MAX) NULL,
    [Purpose_of_Sub_Account]        VARCHAR (MAX) NULL,
    [Number_of_Agent_Locations]     VARCHAR (MAX) NULL,
    CONSTRAINT [PK_WellsFargoReportDetailExcel] PRIMARY KEY CLUSTERED ([idWellsFargoReportDetailExcel] ASC)
);

