CREATE TABLE [dbo].[XAgentFolios] (
    [IdAgent]                            INT            IDENTITY (1, 1) NOT NULL,
    [IdAgentCommunication]               INT            NOT NULL,
    [IdAgentType]                        INT            NOT NULL,
    [IdUserSeller]                       INT            NOT NULL,
    [IdUserOpeningSalesRep]              INT            NULL,
    [IdAgentStatus]                      INT            NOT NULL,
    [IdAgentPaymentSchema]               INT            NOT NULL,
    [IdAgentReceiptType]                 INT            NULL,
    [IdAgentBankDeposit]                 INT            NULL,
    [AgentName]                          NVARCHAR (MAX) NOT NULL,
    [AgentCode]                          NVARCHAR (MAX) NOT NULL,
    [AgentAddress]                       NVARCHAR (MAX) NOT NULL,
    [AgentCity]                          NVARCHAR (MAX) NOT NULL,
    [AgentState]                         NVARCHAR (MAX) NOT NULL,
    [AgentZipcode]                       NVARCHAR (MAX) NOT NULL,
    [AgentPhone]                         NVARCHAR (MAX) NOT NULL,
    [AgentFax]                           NVARCHAR (MAX) NOT NULL,
    [AgentEmail]                         NVARCHAR (MAX) NOT NULL,
    [AgentContact]                       NVARCHAR (MAX) NOT NULL,
    [AgentTimeInBusiness]                NVARCHAR (MAX) NOT NULL,
    [AgentBusinessType]                  NVARCHAR (MAX) NOT NULL,
    [OwnerName]                          NVARCHAR (MAX) NOT NULL,
    [OwnerLastName]                      NVARCHAR (MAX) NULL,
    [OwnerSecondLastName]                NVARCHAR (MAX) NULL,
    [OwnerAddress]                       NVARCHAR (MAX) NOT NULL,
    [OwnerCity]                          NVARCHAR (MAX) NOT NULL,
    [OwnerState]                         NVARCHAR (MAX) NOT NULL,
    [OwnerZipcode]                       NVARCHAR (MAX) NOT NULL,
    [OwnerPhone]                         NVARCHAR (MAX) NOT NULL,
    [OwnerCel]                           NVARCHAR (MAX) NOT NULL,
    [OwnerEmail]                         NVARCHAR (MAX) NOT NULL,
    [OwnerSSN]                           NVARCHAR (MAX) NOT NULL,
    [OwnerIdType]                        NVARCHAR (MAX) NOT NULL,
    [OwnerIdNumber]                      NVARCHAR (MAX) NOT NULL,
    [OwnerIdExpirationDate]              DATE           NULL,
    [OwnerBornDate]                      DATE           NULL,
    [GuarantorName]                      NVARCHAR (MAX) NULL,
    [GuarantorLastName]                  NVARCHAR (MAX) NULL,
    [GuarantorSecondLastName]            NVARCHAR (MAX) NULL,
    [GuarantorAddress]                   NVARCHAR (MAX) NULL,
    [GuarantorCity]                      NVARCHAR (MAX) NULL,
    [GuarantorState]                     NVARCHAR (MAX) NULL,
    [GuarantorZipcode]                   NVARCHAR (MAX) NULL,
    [GuarantorPhone]                     NVARCHAR (MAX) NULL,
    [GuarantorCel]                       NVARCHAR (MAX) NULL,
    [GuarantorEmail]                     NVARCHAR (MAX) NULL,
    [GuarantorSSN]                       NVARCHAR (MAX) NULL,
    [GuarantorIdType]                    NVARCHAR (MAX) NULL,
    [GuarantorIdNumber]                  NVARCHAR (MAX) NULL,
    [GuarantorIdExpirationDate]          DATE           NULL,
    [GuarantorBornDate]                  DATE           NULL,
    [TaxID]                              NVARCHAR (MAX) NOT NULL,
    [CreditAmount]                       MONEY          NOT NULL,
    [Folio]                              INT            NOT NULL,
    [AmountRequiredToAskId]              MONEY          NOT NULL,
    [CreationDate]                       DATETIME       NOT NULL,
    [OpenDate]                           DATETIME       NOT NULL,
    [Notes]                              NVARCHAR (MAX) NOT NULL,
    [CloseDate]                          DATETIME       NOT NULL,
    [BusinessPermissionNumber]           NVARCHAR (MAX) NULL,
    [BusinessPermissionExpiration]       DATE           NULL,
    [DoneOnSundayPayOn]                  INT            NOT NULL,
    [DoneOnMondayPayOn]                  INT            NOT NULL,
    [DoneOnTuesdayPayOn]                 INT            NOT NULL,
    [DoneOnWednesdayPayOn]               INT            NOT NULL,
    [DoneOnThursdayPayOn]                INT            NOT NULL,
    [DoneOnFridayPayOn]                  INT            NOT NULL,
    [DoneOnSaturdayPayOn]                INT            NOT NULL,
    [DateOfLastChange]                   DATETIME       NOT NULL,
    [EnterByIdUser]                      INT            NOT NULL,
    [SwitchCommission]                   BIT            NOT NULL,
    [SwitchExrate]                       BIT            NOT NULL,
    [CommissionTop]                      MONEY          NOT NULL,
    [CommissionBottom]                   MONEY          NOT NULL,
    [ExrateTop]                          MONEY          NOT NULL,
    [ExrateBottom]                       MONEY          NOT NULL,
    [ACHWellsFargo]                      BIT            NOT NULL,
    [county]                             NVARCHAR (MAX) NULL,
    [ShowAgentProfitWhenSendingTransfer] BIT            NOT NULL,
    [OwnerBornCountry]                   NVARCHAR (MAX) NULL,
    [GuarantorBornCountry]               NVARCHAR (MAX) NULL,
    [ExcludeReportSignatureHold]         BIT            NOT NULL,
    [ExcludeReportExRates]               BIT            NOT NULL
);

