CREATE TABLE [MoneyOrder].[AgentRegistration] (
    [IdAgentRegistration]  INT            IDENTITY (1, 1) NOT NULL,
    [IdAgent]              INT            NOT NULL,
    [PIN]                  VARCHAR (20)   NOT NULL,
    [TransactionFee]       MONEY          NOT NULL,
    [GUID]                 VARCHAR (50)   NULL,
    [PrivateKey]           VARCHAR (3000) NULL,
    [PublicKey]            VARCHAR (3000) NULL,
    [EffectiveStartDate]   DATETIME       NULL,
    [EffectiveEndDate]     DATETIME       NULL,
    [RouteCode]            VARCHAR (50)   NULL,
    [AccountNo]            VARCHAR (50)   NULL,
    [CompanyId]            INT            NULL,
    [StoreId]              INT            NULL,
    [IdGenericStatus]      INT            NOT NULL,
    [CreationDate]         DATETIME       NOT NULL,
    [DateOfLastChange]     DATETIME       NOT NULL,
    [EnterByIdUser]        INT            NOT NULL,
    [TransactionFeeTop]    MONEY          CONSTRAINT [DF_AgentRegistration_TransactionFeeTop] DEFAULT ((0)) NOT NULL,
    [TransactionFeeBottom] MONEY          CONSTRAINT [DF_AgentRegistration_TransactionFeeBottom] DEFAULT ((0)) NOT NULL,
    [CommissionToAgent]    TINYINT        CONSTRAINT [DF_AgentRegistration_CommissionToAgent] DEFAULT ((0)) NOT NULL,
    [VerifySequence]       BIT            CONSTRAINT [DF_AgentRegistration_VerifySequence] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AgentRegistration] PRIMARY KEY CLUSTERED ([IdAgentRegistration] ASC),
    CONSTRAINT [FK_AgentRegistration_Agent] FOREIGN KEY ([IdAgent]) REFERENCES [dbo].[Agent] ([IdAgent]),
    CONSTRAINT [FK_AgentRegistration_GenericStatus] FOREIGN KEY ([IdGenericStatus]) REFERENCES [dbo].[GenericStatus] ([IdGenericStatus]),
    CONSTRAINT [FK_AgentRegistration_User] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser]),
    CONSTRAINT [UQ_AgentRegistration_Agent] UNIQUE NONCLUSTERED ([IdAgent] ASC)
);

