CREATE TABLE [MoneyOrder].[SaleRecord] (
    [IdSaleRecord]                       INT           IDENTITY (1, 1) NOT NULL,
    [IdAgent]                            INT           NOT NULL,
    [IdSequence]                         INT           NOT NULL,
    [IdStatus]                           INT           NOT NULL,
    [TransCode]                          INT           NULL,
    [IdCustomer]                         INT           NOT NULL,
    [IdDialingCodePhoneNumber]           INT           NOT NULL,
    [CustomerCelullarNumber]             VARCHAR (200) NOT NULL,
    [CustomerName]                       VARCHAR (200) NOT NULL,
    [CustomerFirstLastName]              VARCHAR (200) NOT NULL,
    [CustomerSecondLastName]             VARCHAR (200) NOT NULL,
    [Maker]                              VARCHAR (200) NOT NULL,
    [Remitter]                           VARCHAR (600) NOT NULL,
    [Payee]                              VARCHAR (600) NOT NULL,
    [Purchaser]                          VARCHAR (600) NOT NULL,
    [RouteCode]                          VARCHAR (200) NULL,
    [AccountNumber]                      VARCHAR (200) NULL,
    [SequenceNumber]                     BIGINT        NOT NULL,
    [WorksheetDate]                      DATETIME      NULL,
    [SaleDate]                           DATETIME      NOT NULL,
    [Amount]                             MONEY         NOT NULL,
    [FeeAmount]                          MONEY         NOT NULL,
    [TotalAmount]                        MONEY         NOT NULL,
    [TotalAmountToCorporate]             MONEY         NOT NULL,
    [AgentCommission]                    MONEY         NOT NULL,
    [CorporateCommission]                MONEY         NOT NULL,
    [ExpirationDate]                     DATETIME      NULL,
    [CustomerHasTaxId]                   BIT           NULL,
    [CustomerIdTypeTaxId]                INT           NULL,
    [CustomerSSN]                        VARCHAR (200) NULL,
    [CustomerHasDuplicatedTaxId]         BIT           NULL,
    [CustomerIdIdentificationType]       INT           NULL,
    [CustomerIdentificationNumber]       VARCHAR (200) NULL,
    [CustomerExpirationIdentification]   DATETIME      NULL,
    [CustomerIdentificationIdCountry]    INT           NULL,
    [CustomerIdentificationIdState]      INT           NULL,
    [CustomerIdCountryOfBirth]           INT           NULL,
    [CustomerBornDate]                   DATETIME      NULL,
    [CustomerIdOccupation]               INT           NULL,
    [CustomerIdSubcategoryOccupation]    INT           NULL,
    [CustomerSubcategoryOccupationOther] VARCHAR (200) NULL,
    [CustomerPurpose]                    VARCHAR (200) NULL,
    [CustomerRelationship]               VARCHAR (200) NULL,
    [CustomerMoneySource]                VARCHAR (200) NULL,
    [CreationDate]                       DATETIME      NOT NULL,
    [DateOfLastChange]                   DATETIME      NOT NULL,
    [EnterByIdUser]                      INT           NOT NULL,
    [IdAgentPaymentSchema]               INT           NOT NULL,
    CONSTRAINT [PK_SaleRecord] PRIMARY KEY CLUSTERED ([IdSaleRecord] ASC),
    CONSTRAINT [FK_Agent_SaleRecord] FOREIGN KEY ([IdAgent]) REFERENCES [dbo].[Agent] ([IdAgent]),
    CONSTRAINT [FK_SaleRecord_AgentPaymentSchema] FOREIGN KEY ([IdAgentPaymentSchema]) REFERENCES [dbo].[AgentPaymentSchema] ([IdAgentPaymentSchema]),
    CONSTRAINT [FK_SaleRecord_Country_CustomerIdentificationIdCountry] FOREIGN KEY ([CustomerIdentificationIdCountry]) REFERENCES [dbo].[Country] ([IdCountry]),
    CONSTRAINT [FK_SaleRecord_Country_IdCountryOfBirth] FOREIGN KEY ([CustomerIdCountryOfBirth]) REFERENCES [dbo].[Country] ([IdCountry]),
    CONSTRAINT [FK_SaleRecord_Customer] FOREIGN KEY ([IdCustomer]) REFERENCES [dbo].[Customer] ([IdCustomer]),
    CONSTRAINT [FK_SaleRecord_DialingCodePhoneNumber] FOREIGN KEY ([IdDialingCodePhoneNumber]) REFERENCES [dbo].[DialingCodePhoneNumber] ([IdDialingCodePhoneNumber]),
    CONSTRAINT [FK_SaleRecord_DictionaryOccupation] FOREIGN KEY ([CustomerIdOccupation]) REFERENCES [dbo].[DictionaryOccupation] ([IdOccupation]),
    CONSTRAINT [FK_SaleRecord_Sequence] FOREIGN KEY ([IdSequence]) REFERENCES [MoneyOrder].[Sequence] ([IdSequence]),
    CONSTRAINT [FK_SaleRecord_State_CustomerIdentificationIdState] FOREIGN KEY ([CustomerIdentificationIdState]) REFERENCES [dbo].[State] ([IdState]),
    CONSTRAINT [FK_SaleRecord_Status] FOREIGN KEY ([IdStatus]) REFERENCES [dbo].[Status] ([IdStatus]),
    CONSTRAINT [FK_SaleRecord_User] FOREIGN KEY ([EnterByIdUser]) REFERENCES [dbo].[Users] ([IdUser])
);

