CREATE PROCEDURE [dbo].[st_AMLPClearSuspiciusAgentLocksByUser]
(
	@IdUser			INT
)
AS
BEGIN
BEGIN TRANSACTION	
	DECLARE @MSG_ERROR NVARCHAR(500)
	BEGIN TRY
		DELETE FROM AMLP_SuspiciousAgentLock WHERE IdUser = @IdUser

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION

		IF(ISNULL(@MSG_ERROR, '') = '')
			SET @MSG_ERROR = ERROR_MESSAGE();

		RAISERROR(@MSG_ERROR, 16, 1);
	END CATCH
END
