
CREATE PROCEDURE [dbo].[st_GetAgentsById] 
	@IdAgent int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	SELECT 
    A.[IdAgent], 
    A.[IdAgentCommunication], 
    A.[IdAgentType], 
    A.[IdUserSeller], 
    A.[IdUserOpeningSalesRep], 
    A.[IdAgentStatus], 
    A.[IdAgentPaymentSchema], 
    A.[IdAgentReceiptType], 
    A.[IdAgentBankDeposit], 
    A.[IdAgentCollectType], 
    A.[IdOwner], 
    A.[AgentName], 
    A.[AgentCode], 
    A.[StateCode], 
    A.[AgentAddress], 
    A.[AgentCity], 
    A.[AgentState], 
    A.[AgentZipcode], 
    A.[AgentFax], 
    A.[AgentPhone], 
    A.[AgentEmail], 
    A.[AgentContact], 
    A.[AgentTimeInBusiness], 
    A.[AgentBusinessType], 
    A.[GuarantorName], 
    A.[GuarantorLastName], 
    A.[GuarantorSecondLastName], 
    A.[GuarantorAddress], 
    A.[GuarantorCity], 
    A.[GuarantorState], 
    A.[GuarantorZipcode], 
    A.[GuarantorPhone], 
    A.[GuarantorCel], 
    A.[GuarantorEmail], 
    A.[GuarantorSSN], 
    A.[GuarantorIdType], 
    A.[GuarantorIdNumber], 
    A.[GuarantorIdExpirationDate], 
    A.[GuarantorBornDate], 
    A.[TaxID], 
    A.[CreditAmount], 
    A.[AmountRequiredToAskId], 
    A.[OpenDate], 
    A.[Notes], 
    A.[CloseDate], 
    A.[BusinessPermissionNumber], 
    A.[BusinessPermissionExpiration], 
    A.[DoneOnSundayPayOn], 
    A.[DoneOnMondayPayOn], 
    A.[DoneOnTuesdayPayOn], 
    A.[DoneOnWednesdayPayOn], 
    A.[DoneOnThursdayPayOn], 
    A.[DoneOnFridayPayOn], 
    A.[DoneOnSaturdayPayOn], 
    A.[SwitchCommission], 
    A.[SwitchExrate], 
    A.[CommissionTop], 
    A.[CommissionBottom], 
    A.[ExrateTop], 
    A.[ExrateBottom], 
    A.[ShowAgentProfitWhenSendingTransfer], 
    A.[GuarantorBornCountry], 
    A.[ExcludeReportSignatureHold], 
    A.[ExcludeReportExRates], 
    A.[ShowLogo], 
    A.[CancelReturnCommission], 
    A.[IdAgentClass], 
    A.[AccountNumber], 
    A.[RoutingNumber], 
    A.[RetainMoneyCommission], 
    A.[DoingBusinessAs], 
    A.[IdAgentCommissionPay], 
    A.[subAccount], 
    A.[AccountNumberCommission], 
    A.[RoutingNumberCommission], 
    A.[UsePIN], 
    A.[UsePayNow], 
    A.[IdCounty], 
    A.[IdCountyGuarantor], 
    A.[SuspendedDatePendingFile], 
    A.[BlockPhoneTransactions], 
    A.[MoneyAlertInvitation], 
    A.[CheckEditMicr], 
    A.[IdTimeZone], 
    A.[NeedsWFSubaccount], 
    A.[RequestWFSubaccount], 
    A.[CreationDate], 
    A.[DateOfLastChange], 
    A.[EnterByIdUser], 
    SA.[IdAgentStatus] AS [IdAgentStatus1], 
    SA.[AgentStatus], 
    SA.[VisibleForUser]
    FROM  [dbo].[Agent] AS A WITH(NOLOCK)
    INNER JOIN [dbo].[AgentStatus] AS SA WITH(NOLOCK) ON A.[IdAgentStatus] = SA.[IdAgentStatus]
    WHERE A.[IdAgentCollectType] IN (1, 2, 3, 4, 5, 6, 7, 8) AND A.IdAgent = @IdAgent

END 




