CREATE TABLE [MoneyGram].[Transaction] (
    [IdTransaction]             INT           IDENTITY (1, 1) NOT NULL,
    [IdPreTransfer]             INT           NOT NULL,
    [IdTransfer]                INT           NULL,
    [MgiTransactionSessionID]   VARCHAR (40)  NOT NULL,
    [CustomerReceiveNumber]     VARCHAR (30)  NULL,
    [DisplayAccountID]          VARCHAR (300) NULL,
    [CustomerServiceMessage]    VARCHAR (300) NULL,
    [AccountNickname]           VARCHAR (40)  NULL,
    [ReadyForCommit]            BIT           NOT NULL,
    [ReceiveAgentName]          VARCHAR (50)  NULL,
    [ReceiveAgentAddress]       VARCHAR (400) NOT NULL,
    [SendAmount]                MONEY         NULL,
    [SendCurrency]              VARCHAR (10)  NULL,
    [TotalSendFees]             MONEY         NULL,
    [TotalDiscountAmount]       MONEY         NULL,
    [TotalSendTaxes]            MONEY         NULL,
    [TotalAmountToCollect]      MONEY         NULL,
    [ReceiveAmount]             MONEY         NULL,
    [ReceiveCurrency]           VARCHAR (10)  NULL,
    [ValidCurrencyIndicator]    BIT           NULL,
    [PayoutCurrency]            VARCHAR (10)  NULL,
    [TotalReceiveFees]          MONEY         NULL,
    [TotalReceiveTaxes]         MONEY         NULL,
    [TotalReceiveAmount]        MONEY         NULL,
    [ReceiveFeesAreEstimated]   BIT           NULL,
    [ReceiveTaxesAreEstimated]  BIT           NULL,
    [ExchangeRateApplied]       MONEY         NULL,
    [ReceiveFeeDisclosureText]  BIT           NULL,
    [ReceiveTaxDisclosureText]  BIT           NULL,
    [ConfirmationNumber]        VARCHAR (20)  NULL,
    [ReferenceNumber]           VARCHAR (20)  NULL,
    [PartnerConfirmationNumber] VARCHAR (20)  NULL,
    [PartnerName]               VARCHAR (200) NULL,
    [FreePhoneCallPIN]          VARCHAR (20)  NULL,
    [TollFreePhoneNumber]       VARCHAR (20)  NULL,
    [ExpectedDateOfDelivery]    DATETIME      NULL,
    [TransactionDateTime]       DATETIME      NULL,
    [EnterByIdUser]             INT           NOT NULL,
    [CreationDate]              DATETIME      NOT NULL,
    [IdUserLastUpdate]          INT           NULL,
    [DateOfLastChange]          DATETIME      NULL,
    [OriginalClaimCode]         VARCHAR (200) NULL,
    CONSTRAINT [PK_MoneyGramTransaction] PRIMARY KEY CLUSTERED ([IdTransaction] ASC),
    CONSTRAINT [UQ_MoneyGramTransaction_IdPreTransfer] UNIQUE NONCLUSTERED ([IdPreTransfer] ASC)
);

