CREATE TABLE [InternalSalesMonitor].[Details] (
    [IdDetail]           INT            IDENTITY (1, 1) NOT NULL,
    [IdAgent]            INT            NOT NULL,
    [ContacName]         NVARCHAR (MAX) NOT NULL,
    [SendFax]            BIT            NOT NULL,
    [SundayStart]        TIME (0)       NULL,
    [SundayEnd]          TIME (0)       NULL,
    [SundayClosed]       BIT            NOT NULL,
    [MondayStart]        TIME (0)       NULL,
    [MondayEnd]          TIME (0)       NULL,
    [MondayClosed]       BIT            NOT NULL,
    [TuesdayStart]       TIME (0)       NULL,
    [TuesdayEnd]         TIME (0)       NULL,
    [TuesdayClosed]      BIT            NOT NULL,
    [WednesdayStart]     TIME (0)       NULL,
    [WednesdayEnd]       TIME (0)       NULL,
    [WednesdayClosed]    BIT            NOT NULL,
    [ThursdayStart]      TIME (0)       NULL,
    [ThursdayEnd]        TIME (0)       NULL,
    [ThursdayClosed]     BIT            NOT NULL,
    [FridayStart]        TIME (0)       NULL,
    [FridayEnd]          TIME (0)       NULL,
    [FridayClosed]       BIT            NOT NULL,
    [SaturdayStart]      TIME (0)       NULL,
    [SaturdayEnd]        TIME (0)       NULL,
    [SaturdayClosed]     BIT            NOT NULL,
    [EnterByIdUser]      INT            NOT NULL,
    [CreationDate]       DATETIME       NOT NULL,
    [LastChangeByIdUser] INT            NULL,
    [DateOfLastChange]   DATETIME       NULL,
    CONSTRAINT [PK_DetailsAgent] PRIMARY KEY CLUSTERED ([IdDetail] ASC) WITH (FILLFACTOR = 90)
);

