create FUNCTION [dbo].[fn_GetCustomerC]
    (@strAlphaNumeric NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
 RETURN 
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
    replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
	replace(
    upper(@strAlphaNumeric)   
	,'AAAA','A')    
	,'BBBB','B')    
	,'CCCC','C')    
	,'DDDD','D')    
	,'EEEE','E')    
	,'FFFF','F')    
	,'GGGG','G')    
	,'HHHH','H')    
	,'IIII','I')    
	,'JJJJ','J')    
	,'KKKK','K')    
	,'LLLL','Y')    
	,'MMMM','M')    
	,'NNNN','N')    
	,'OOOO','O')    
	,'PPPP','P')    
	,'QQQQ','Q')    
	,'RRRR','R')    
	,'SSSS','S')    
	,'TTTT','T')    
	,'UUUU','U')    
	,'VVVV','V')    
	,'WWWW','W')    
	,'XXXX','X')    
	,'YYYY','Y')    
	,'ZZZZ','Z')  
	,'AAA','A')    
	,'BBB','B')    
	,'CCC','C')    
	,'DDD','D')    
	,'EEE','E')    
	,'FFF','F')    
	,'GGG','G')    
	,'HHH','H')    
	,'III','I')    
	,'JJJ','J')    
	,'KKK','K')    
	,'LLL','YL')    
	,'MMM','M')    
	,'NNN','N')    
	,'OOO','O')    
	,'PPP','P')    
	,'QQQ','Q')    
	,'RRR','R')    
	,'SSS','S')    
	,'TTT','T')    
	,'UUU','U')    
	,'VVV','V')    
	,'WWW','W')    
	,'XXX','X')    
	,'YYY','Y')    
	,'ZZZ','Z')  
    ,'AA','A')    
	,'BB','B')    
	,'CC','C')    
	,'DD','D')    
	,'EE','E')    
	,'FF','F')    
	,'GG','G')    
	,'HH','H')    
	,'II','I')    
	,'JJ','J')    
	,'KK','K')    
	,'LL','Y')    
	,'MM','M')    
	,'NN','N')    
	,'OO','O')    
	,'PP','P')    
	,'QQ','Q')    
	,'RR','R')    
	,'SS','S')    
	,'TT','T')    
	,'UU','U')    
	,'VV','V')    
	,'WW','W')    
	,'XX','X')    
	,'YY','Y')    
	,'ZZ','Z')    	 
    ,'CE','SE')    
    ,'CI','SI')    
    ,'ZA','SA')    
    ,'ZE','SE')    
    ,'ZI','SI')    
    ,'ZO','SO')    
    ,'ZU','SU')    
    ,'GE','JE')    
    ,'GI','JI')    
    ,'VA','BA')    
    ,'VE','BE')    
    ,'VI','BI')    
    ,'VO','BO')    
    ,'VU','BU')        
	,'AZ','AS')
	,'EZ','ES')
	,'IZ','IS')
	,'OZ','OS')
	,'UZ','US')
    ,' ','')
    ,'.','')    
END