 /********************************************************************
<Author>Not Known</Author>
<app>Maxi WinServices CollectionReport</app>
<Description></Description>

<ChangeLog>
<log Date="15/07/2020" Author="bortega">Ticket 2072 Autogenerated Reports - Collection Report. Req:: 00197</log>
</ChangeLog>
********************************************************************/
CREATE procedure [dbo].[st_ReportDepositCollectPlan]      
 (      
	 @StartDate Datetime,      
	 @EndDate Datetime      
 )      
 as 
 
 Begin try
 --Req:: 00197     
	 Set @StartDate=dbo.RemoveTimeFromDatetime(@StartDate)      
	 --Set @EndDate=dbo.RemoveTimeFromDatetime(@EndDate+1)      
	 DECLARE @HourNow varchar(50)
		set @HourNow = (select CONVERT(VARCHAR(12), GETDATE(), 114) AS [HH:MI:SS:MMM(24H)])
		--set @HourNow = '02:00:00.000'
	   
		if(@HourNow >= '01:10:00' AND @HourNow < '09:00:00')
			BEGIN
				SET @EndDate =dbo.RemoveTimeFromDatetime(@EndDate) 
		   END
		ELSE
			BEGIN
				SET @EndDate =dbo.RemoveTimeFromDatetime(@EndDate+1) 
			END
--Req:: 00197
    
	 Set nocount on       
		 Select      
		 B.AgentCode +' '+B.AgentName as Agent, 
		 A.AmountToPay as Amount,    
		 A.DateofLastChange as Entry, 
		 A.Note as Note,
		 U.UserName   	 
		 from AgentCollectionDetail A with(nolock)   
		 join AgentCollection AC with(nolock) on (A.IdAgentCollection = AC.IdAgentCollection)
		 Join Agent B with(nolock)  on (AC.IdAgent=B.IdAgent)   
		 join users U with(nolock) on U.IdUser= A.EnterByIdUser
		 join AgentCollectionConcept ACC with(nolock) on (ACC.IdAgentCollectionConcept = A.IdAgentCollectionConcept)
		 where A.DateOfLastChange>@StartDate and A.DateOfLastChange<@EndDate and A.AmountToPay > 0 and ACC.Name = 'Manual'

End try
Begin Catch    
DECLARE @ErrorMessage varchar(max)                                                                 
    Select @ErrorMessage=ERROR_MESSAGE()   
    Insert into ErrorLogForStoreProcedure (StoreProcedure,ErrorDate,ErrorMessage)Values('st_ReportDepositCollectPlan',Getdate(),@ErrorMessage)
End catch